sonar.projectKey=org.sonarqube:mortgage-loan-injection
sonar.projectName=Golang :: SonarQube Scanner :: mortgage-loan-injection
sonar.projectVersion=ver:v0.1.0

sonar.language=go
sonar.sources=.
sonar.sourceEncoding=UTF-8

# if you want disabled the DTD verification for a proxy problem for example, true by default
sonar.coverage.dtdVerification=false

sonar.exclusions=**/*_test.go,**/vendor/**,**/cmd/**,**/mocks/**,**/internal/infra/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=**/vendor/**
sonar.go.coverage.reportPaths=coverfile_out
